### ISSUE TITLE
Hackerspace Goal Setting for Returning Students Requires the Alumni Badge

### ISSUE THREAD

**Issue by fjbagley** [timberline-secondary/hackerspace-todo#206]
You can only access the [goal setting for returning students](https://hackerspace.bytedeck.com/quests/1314/) quest if you have the alumni badge, but you need to complete this quest in order to get the alumni badge.

**Comment by tylerecouture** [comment]
Suggested solution? I don't see a way around this, or I'm not sure what the problem is.  In Hackerspace Alumni badge is always granted manually before this quest.  3rd and 4th badges are granted after this.

**Comment by fjbagley** [comment]
From the quest: "The reward for completing this quest is your 20 XP Alumni badge (or equivalent)." 

I didn't realize you gave the badge before students completed the quest. If you do, then the above sentence doesn't make sense. 

I have the prerequisite as the Proficiency badge, but this brings challenges of its own - new students sometimes won't read the quest and complete it.

2 possible solutions: 
- Future time release feature of quest. This quest could only be completed after a quarter's worth of hours have elapsed since doing the Welcome quest.
- Grant the badge at the start of the year and make it somehow mandatory to complete this quest before going on to other quests as a returning user. Perhaps along with the class contract renewal?

**Comment by tylerecouture** [comment]
Oh good catch.  That sentence doesn't make sense any more.

I use this as a reminder for me to grant them their 3rd and 4th course  badges, because there's no automated way of doing it.

Your second solution is already in effect because it's a blocking quest: I grant Alumni at the beginning of the course, and then they must complete this.

If they already have the Alumni from a previous course (meaning this is their 3rd+ course) then this quest will automatically appear and block them.

**Comment by tylerecouture** [comment]
I removed the section about returning students only, because new student will never see it with how it's set up now.

**Comment by fjbagley** [comment]
I didn't realize the blocking feature was already available. Nice!
